name: admin_thrifters
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  thrifters_classes:
    path: ../admin_thrifters/thrifters_classes

  firebase_core:
  cupertino_icons: ^1.0.2
  connectivity_plus: ^2.2.1
  modal_bottom_sheet: ^2.0.0
  firebase_auth:
  cloud_firestore:
  firebase_messaging: ^11.1.0
  modal_progress_hud: ^0.1.3
  auto_size_text:
  cached_network_image: ^3.1.0
  font_awesome_flutter:
  geolocator:
  google_fonts: ^2.1.0
  intl:
  page_transition:
  provider:
  timeago:
  url_launcher:
  firebase_storage:
  fluttertoast: ^8.0.8
  rounded_loading_button: ^2.0.9
  page_view_dot_indicator: ^1.0.0
  file_picker: ^4.1.3
  data_table_2: ^2.1.1
  printing: ^5.6.0
  barcode: ^2.1.0
  esc_pos_printer: ^4.1.0
  flutter_local_notifications: ^5.0.0+4
  rxdart: ^0.26.0-nullsafety.1
  quiver: ^3.0.1+1
  dropdown_search: ^2.0.1



dev_dependencies:
  flutter_native_splash: ^1.2.0
  flutter_launcher_icons: "^0.9.1"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#f7f7f7"


flutter_native_splash:
  color: "#f7f7f7"
  image: assets/thrifter.png
  android: true
  ios: true

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  fonts:
    - family: Style Script
      fonts:
        - asset: assets/StyleScript-Regular.ttf

  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/

